config/routes.rb
Alumni::Application.routes.draw do
scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root :to => 'main#index'
  resources :users do
    resources :links
  end
  resources :users do
    collection { post :search, to: 'users#index' }
  end
  resources :users do
    resources :videos
  end
  resources :projects do
    resources :links
  end
  resources :videos
  resources :links
  resources :addresses
  get 'remote%2FgetStates%2F:country', to:'addresses#getStates'
  resources :users do
    resources :inquiries, :only => [:new, :create] do
      get 'thank_you', :on => :collection
    end
  end
end
match '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
match '', to: redirect("/#{I18n.locale}")

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauth_providers => [:twitter]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
    :remember_me, :first_name, :last_name, :phone_number,
    :introduction, :desired_job_situation, :desired_job_location,
    :skills, :preferred_language, :username, :twitter_handle, :image
  # attr_accessible :title, :body

  validates_presence_of :username
  validates_uniqueness_of :username
  # validates_format_of :twitter_handle, :with => /^@[a-zA-Z0-9]+$/,
    # :message => "Must start with @ and have no spaces"

  has_one :address
  has_many :projects
  has_many :videos
  has_many :links, :as => :owner
  delegate :street_address, :city, :state, :postal_code, :country,
            :to => :address,
            :allow_nil => true

  mount_uploader :image, UserImageUploader

  def self.ransackable_attributes(auth_object = nil)
    %w( email first_name last_name phone_number introduction desired_job_situation desired_job_location skills preferred_language username twitter_handle ) + _ransackers.keys
  end

  def display_address
    city.to_s +
      (state.present? ? (", " + address.state_name) : "") +
      (country.present? ? (", " + address.country_name) : "")
  end

  def User.language_options
    return [
      "English",
      "中文"
    ]
  end

  def preferred_language_abbreviation
    return self.preferred_language.to_s.slice(0,2).downcase.to_sym
  end

  def full_name
    return (self.first_name.nil? ? '' : self.first_name) + ' ' +
      (self.last_name.nil? ? '' : self.last_name)
  end

  def ordered_links
    return self.links.sort_by { |link| link.url_type}
  end

  def associated_user
    return self
  end

  def random_project_title
    proj = self.random_project
    if proj.nil?
      return ''
    else
      return proj.title
    end
  end

  def random_project
    @projects = self.projects
    if @projects.empty?
      return nil
    else
      return @projects.at(Random.rand(@projects.size))
    end
  end

  def self.from_omniauth(auth)
    user_by_twitter = where("twitter_handle = ?", ("@" + auth.extra.raw_info.screen_name))
    if user_by_twitter.first
      return user_by_twitter.first
    end
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      screen_name = auth.extra.raw_info.screen_name
      if screen_name.present?
        user.twitter_handle = "@" + auth.extra.raw_info.screen_name
      end
      user.introduction = auth.extra.raw_info.description
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def self.search_skills(search)
    if search.present?
      strings = search.downcase.split
      self.all.select do |user|
        (strings.select {|skill| user.skills.to_s.downcase.include? skill}).count == strings.count
      end
    else
      self.all
    end
  end


  def self.search_name(search)
    strings = search.downcase.split
    search_results = Array.new
    exact_match_count = 0
    self.all.each  do |e|
      if ( e.first_name.to_s.downcase == strings.first && e.last_name..to_s.downcase == strings.last )
        search_results.insert(0,e)
        exact_match_count += 1
      end
      if ( (strings.include? e.first_name.to_s.downcase) && (strings.include? e.last_name.to_s.downcase) )
        search_results.insert(exact_match_count, e)
      end
      if ( (strings.include? e.first_name.to_s.downcase) || (strings.include? e.last_name.to_s.downcase) )
        search_results << e
      end
    end
    search_results
  end

  def relevant_link
    link = links.detect { |e| e.home_page? } || links.shuffle.first
    if link
      link.url_text
    else
      nil
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @search = User.search(params[:q])
    @search.build_condition if @search.conditions.empty?
    if params[:search_name].present?
      @users = User.search_name(params[:search_name]).uniq
    elsif params[:search_skills].present?
      @users = User.search_skills(params[:search_skills]).uniq
    elsif params[:q].present?
      @users = @search.result(distinct: true)
    else
      @users = User.all
    end
  end

  def show
    @object = @user
  end

  def create
    @user = User.create( params[:user] )
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Profile has been updated."
      redirect_to @user
    else
      flash[:alert] = "Profile has not been updated."
      render :action => "edit"
    end
  end

private
  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_attachment_form.html.erb
<%= form_for @user do |f| %>
  <table class="table table-striped table-bordered">
    <thead>
      <th>Url</th>
      <th>Link Type</th>
      <th>Link Description</th>
     </thead>
     <tbody>
       <% @object.ordered_links.each do |link| %>
         <tr>
           <td><a href=<%= link.url_text %> target="_blank"><%= link.url_text %></a>
           <td><%= link.url_type %></td>
           <td><%= link.description %></td>
           <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_link_path(link) %></td>
            <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           <% end %>
         </tr>
       <% end %>
     </tbody>
  </table>
<% end %>

app/views/users/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select associations: [:address, :projects, :links] %>
  <% end %>
  <%= f.predicate_select %>
  <div style="padding:20px 0;">
    <%= f.value_fields do |v| %>
      <%= v.text_field :value %>
    <% end %>
  </div>
  <%= link_to (t "users.index.remove"), '#', class: "remove_fields" %>
</div>

app/views/users/_search_name.html.erb
<%= form_tag users_path, :method => 'get' do %>
  <div>
    <div class="col-sm-3" style="float:left">
      <%= text_field_tag :search_name, params[:search_name], :id => 'search_name_field', class: "form-control" %>
    </div>
    <div style="float:left"><%= submit_tag t "users.index.search_name", :name => nil %></div>
  </div>
<% end %>

app/views/users/_search_skills.html.erb
<%= form_tag users_path, :method => 'get' do %>
  <div>
    <div class="col-sm-3" style="float:left">
      <%= text_field_tag :search_skills, params[:search_skills], :id => 'search_skills_field', class: "form-control" %>
    </div>
    <div style="float:left"><%= submit_tag t "users.index.search_skills", :name => nil %></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<body>
  <section class="hbox stretch">
    <!-- .aside -->
    <aside class="bg-dark aside-md" id="nav">
      <section class="vbox">
        <header class="bg-dark nav-bar">
          <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="body">
            <i class="icon-reorder"></i>
          </a>
          <span class="nav-brand"><%= link_to "Home", root_path %></span>
          <a class="btn btn-link visible-xs" data-toggle="class:show" data-target=".nav-user">
            <i class="icon-comment-alt"></i>
          </a>
        </header>
        <footer class="footer bg-gradient hidden-xs">
          <a href="#nav" data-toggle="class:nav-vertical" class="btn btn-sm btn-link m-l-n-sm">
            <i class="icon-reorder"></i>
          </a>
        </footer>
        <section>
          <% if current_user == @user %>
            <div class="bg-dark lter nav-user hidden-xs pos-rlt">
              <div class="nav-avatar pos-rlt">
                <a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown">
                  <%= image_tag @user.image_url(:medium).to_s %>
                  <span class="caret caret-white"></span>
                </a>
                <ul class="dropdown-menu m-t-sm animated fadeInLeft">
                  <span class="arrow top"></span>
                  <li>
                    <%= link_to (t "application.home"), root_path %>
                  </li>
                  <li>
                    <%= link_to (t "application.alumni"), users_path %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <% if current_user == @user %>
                      <% if @user.display_address.present? %>
                        <%= link_to (t ".change_address"), edit_address_path(@user.address) %>
                      <% else %>
                        <%= link_to (t ".add_address"), new_address_path %>
                      <% end %>
                    <% end %>
                  </li>
                  <li>
                    <% if current_user == @user %>
                      <%= link_to (t ".edit_profile"), edit_user_path(@user) %>
                    <% end %>
                  </li>
                  <% if user_signed_in? %>
                    <li><%= link_to (t "application.my_profile"), current_user %></li>
                    <li><%= link_to (t "application.my_projects"), projects_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
                  <% else %>
                    <li><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
                    <li><%= link_to (t "application.sign_in"), new_user_session_path %></li>
                    <li><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
                  <% end %>
                    <li class="divider"></li>
                    <li><a href="https://www.codefellows.org/" target="0">Code Fellows Site</a></li>
                </ul>
              </div>
            </div>
          <% end %>
          <nav class="nav-primary hidden-xs">
            <ul class="nav">
              <li>
                <%= link_to "View All Alumni", users_path %>
              </li>
              <li>
                <a href="http://www.codefellows.org" target="_blank">Code Fellows Website</a>
              </li>
              <% if current_user == @user %>
                <li>
                  <%= link_to (t "application.edit_profile"), edit_user_path(@user) %>
                </li>
              <% end %>
              <% if current_user == @user %>
                <% if @user.display_address.present? %>
                  <li><%= link_to (t " .change_address" ), edit_address_path(@user.address) %></li>
                <% else %>
                  <li><%= link_to (t " .add_address"), new_address_path %></li>
                <% end %>
              <% end %>
              <% if current_user == @user %>
                <li><%= link_to (t "application.my_profile"), current_user %></li>
                <li><%= link_to (t "application.my_projects"), projects_path %></li>
                <li><%= link_to "My Videos", videos_path %></li>
              <% end %>
            </ul>
          </nav>
        </section>
      </section>
    </aside>
    <!-- .aside -->
    <section id="content">
      <section class="vbox">
        <section class="scrollable wrapper">
          <div class="tab-content">
            <section class="tab-pane active" id="basic">
              <span class="nav-brand" href="index.html"><%= t "application.edit_profile" %></span>
              <%= render "form" %>
            </section>
          </div>
        </section>
      </section>
    </section>
    <!-- /.vbox -->
  </section>
</body>
</html>

app/views/users/index.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>

  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">Code Fellows Network</span>


    <section class="scrollable wrapper">

      <div class="col-md-12 col-md-offset-0">
        <div class="col-md-6">
          <section class="panel">
            <div class="panel-body">
              <div id=".search_skills">
                <%= render :partial => 'search_skills' %>
              </div>
              <div id=".search_name">
                <%= render :partial => 'search_name' %>
              </div>
            </div>
          </section>
        </div>
        <div class="col-md-6">
          <section class="panel">
            <div class="panel-body" style="padding-top:18px;padding-bottom:18px;">
              <%= link_to (t ".advanced_search"), '#', class: "show_advanced_search btn-sm btn-success" %>
              <div id="advanced_search" style="padding-top:20px;">
                <%= search_form_for @search do |f| %>
                  <%= f.condition_fields do |c| %>
                    <%= render "condition_fields", f: c %>
                  <% end %>
                  <p><%= link_to_add_fields (t ".add_conditions"), f, :condition %></p>
                  <div class="actions"><%= f.submit (t ".search") %></div>
                <% end %>
              </div>
            </div>
          </section>
        </div>
      </div>
      <div class="link">
        <%= link_to (t ".view_all_alumni"), users_path %>
      </div>
    </section>



    <section class="scrollable wrapper">
      <% @users.each do |user| %>
        <div class="col-md-12">
          <div class="col-lg-4" style="float:left">
            <section class="panel">
              <div class="panel-body">
                <div class="clearfix m-b">
                  <%= link_to (image_tag user.image_url(:thumb).to_s, class: "img-circle"), user, class: "thumb-sm pull-left m-r" %>
                  <div class="clear">
                    <strong><%= link_to user.full_name.to_s, user %></strong>
                    <small class="block text-muted">
                      <% if user.display_address.present? %>
                        <%= " " + user.display_address + " " %>
                      <% end %>&nbsp;&nbsp;
                      <% if user.twitter_handle.present? %>
                        <i class="icon-twitter"></i><%= link_to user.twitter_handle, "https://twitter.com/" + user.twitter_handle, target: '_blank' %>
                      <% end %>
                    </small>
                  </div>
                </div>
                <b>About Me</b>
                <p>
                  <%= user.introduction.to_s.truncate(140, :separator => ' ', :omission => "...") %>
                </p>
                <b>My Skills</b>
                <p>
                  <%= user.skills.to_s.truncate(140, :separator => ' ', :omission => '...') %>
                </p>
              </div>
              <footer class="panel-footer pos-rlt">
                <form class="pull-out">
                  <span class="form-control no-border input-lg text-sm">
                    <%= link_to "Read More", user %>
                  </span>
                </form>
              </footer>
            </section>
          </div>
        </div>
      <% end %>
    </section>
  </section>

  </section>
</body>

app/views/users/new.html.erb
<div class="container_inner">
<% if user_signed_in? %>
    <div class="signed_in">
      <p style="color:#555; line-height:16px; margin:0px;"><%= t "application.signed_in_as" %> <%= current_user.email %></p>
    </div>
<% end %>

<%= link_to (t "application.back"), :back %>
<h2><%= t "application.create_profile" %></h2>
<%= render "form" %>
</div>

app/views/users/search.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :first_name_cont %>
  <%= f.text_field :last_name_cont %>
  <%= f.label :skills_cont %>
  <%= f.text_field :skills_cont %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<body>
  <section class="hbox stretch">
    <!-- .aside -->
    <aside class="bg-dark aside-md" id="nav">
      <section class="vbox">
        <header class="bg-dark nav-bar">
          <a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="body">
            <i class="icon-reorder"></i>
          </a>
          <span class="nav-brand"><%= link_to "Home", root_path %></span>
          <a class="btn btn-link visible-xs" data-toggle="class:show" data-target=".nav-user">
            <i class="icon-comment-alt"></i>
          </a>
        </header>
        <footer class="footer bg-gradient hidden-xs">
          <a href="#nav" data-toggle="class:nav-vertical" class="btn btn-sm btn-link m-l-n-sm">
            <i class="icon-reorder"></i>
          </a>
        </footer>
        <section>
          <% if current_user == @user %>
            <div class="bg-dark lter nav-user hidden-xs pos-rlt">
              <div class="nav-avatar pos-rlt">
                <a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown">
                  <%= image_tag @user.image_url(:medium).to_s %>
                  <span class="caret caret-white"></span>
                </a>
                <ul class="dropdown-menu m-t-sm animated fadeInLeft">
                  <span class="arrow top"></span>
                  <li>
                    <%= link_to (t "application.home"), root_path %>
                  </li>
                  <li>
                    <%= link_to (t "application.alumni"), users_path %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <% if current_user == @user %>
                      <% if @user.display_address.present? %>
                        <%= link_to (t ".change_address"), edit_address_path(@user.address) %>
                      <% else %>
                        <%= link_to (t ".add_address"), new_address_path %>
                      <% end %>
                    <% end %>
                  </li>
                  <li>
                    <% if current_user == @user %>
                      <%= link_to (t ".edit_profile"), edit_user_path(@user) %>
                    <% end %>
                  </li>
                  <% if user_signed_in? %>
                    <li><%= link_to (t "application.my_profile"), current_user %></li>
                    <li><%= link_to (t "application.my_projects"), projects_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
                  <% else %>
                    <li><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
                    <li><%= link_to (t "application.sign_in"), new_user_session_path %></li>
                    <li><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
                  <% end %>
                    <li class="divider"></li>
                    <li><a href="https://www.codefellows.org/" target="0">Code Fellows Site</a></li>
                </ul>
              </div>
            </div>
          <% end %>
          <nav class="nav-primary hidden-xs">
            <ul class="nav">
              <li>
                <%= link_to "View All Alumni", users_path %>
              </li>
              <li>
                <a href="http://www.codefellows.org" target="_blank">Code Fellows Website</a>
              </li>
              <% if current_user == @user %>
                <li>
                  <%= link_to (t "application.edit_profile"), edit_user_path(@user) %>
                </li>
              <% end %>
              <% if current_user == @user %>
                <% if @user.display_address.present? %>
                  <li><%= link_to (t " .change_address" ), edit_address_path(@user.address) %></li>
                <% else %>
                  <li><%= link_to (t " .add_address"), new_address_path %></li>
                <% end %>
              <% end %>
              <% if current_user == @user %>
                <li><%= link_to (t "application.my_profile"), current_user %></li>
                <li><%= link_to (t "application.my_projects"), projects_path %></li>
                <li><%= link_to "My Videos", videos_path %></li>
              <% end %>
            </ul>
          </nav>
        </section>
      </section>
    </aside>
    <!-- /.aside -->
    <!-- .vbox -->
    <section id="content">
      <section class="vbox">
        <header class="header bg-white b-b">
          <p>Welcome to <%= @user.first_name %>'s profile</p>
        </header>
        <section class="scrollable">
          <section class="hbox stretch">
            <aside class="aside-large bg-light lter b-r">
              <section class="vbox">
                <section class="scrollable">
                  <div class="wrapper">
                    <div class="clearfix m-b">
                      <%= image_tag @user.image_url(:medium).to_s, class: "pull-left thumb m-r" %>
                      <div class="clear">
                        <div class="h3 m-t-xs m-b-xs"><%= @user.full_name %></div>
                        <small class="text-muted">
                          <% if @user.display_address.present? %>
                            <%= " " + @user.display_address + " " %>
                          <% end %>
                        </small></br>
                        <small class="text-muted">
                          <% if @user.phone_number.present? %>
                             <%= @user.phone_number %>
                          <% end %>
                        </small>
                      </div>
                    </div>
                    <div class="btn-group btn-group-justified m-b">
                      <% if current_user == @user %>
                        <%= link_to (t ".edit_profile"), edit_user_path(@user), class: "btn btn-success btn-rounded" %>
                      <% else %>
                        <% if @user.twitter_handle.present? %>
                          <a class="btn btn-success btn-rounded" href="http://twitter.com/<%= @user.twitter_handle %>" target="_blank">
                            <i class="icon-twitter"></i>
                            Follow
                          </a>
                        <% end %>
                      <% end %>
                      <% if current_user == @user %>
                        <% if @user.display_address.present? %>
                          <%= link_to "Edit Address", edit_address_path(@user.address), class: "btn btn-info btn-rounded" %>
                        <% else %>
                          <%= link_to (t ".add_address"), new_address_path, class: "btn btn-info btn-rounded" %>
                        <% end %>
                      <% else %>
                        <%= link_to (t ".contact_me"), new_user_inquiry_path(@user), class: "btn btn-info btn-rounded" %>
                      <% end %>
                    </div>
                    <div>
                      <span class="text-uc text-muted"><b>about me</b></span>
                      <p><%= @user.introduction %></p>
                      <span class="text-uc text-muted"><b>my skills</b></span>
                      <p><%= @user.skills %></p>
                      <span class="text-uc text-muted"><b>Dream Job</b></span>
                      <p><%= @user.desired_job_situation %></p>
                      <span class="text-uc text-muted"><b>Dream Location</b></span>
                      <p><%= @user.desired_job_location %></p>
                      <div class="line"></div>
                    </div>
                  </div>
                </section>
              </section>
            </aside>
            <aside class="bg-white">
              <section class="vbox">
                <header class="header bg-light bg-gradient">
                  <ul class="nav nav-tabs nav-white">
                    <li class="active"><a href="#pagelinks" data-toggle="tab">Other Pages</a></li>
                    <li class=""><a href="#myprojects" data-toggle="tab">My Projects</a></li>
                    <li class=""><a href="#myvideos" data-toggle="tab">My Videos</a></li>
                  </ul>
                </header>
                <section class="scrollable">
                  <div class="tab-content">
                    <div class="tab-pane active" id="pagelinks">
                      <%= render "links/links_form" %>
                      <div style="padding:10px 20px;">
                        <% if current_user == @user %>
                          <%= link_to "Add New", new_user_link_path(@user), id: "new_user_link", remote: true %>
                        <% end %>
                      </div>
                    </div>
                    <div class="tab-pane" id="myprojects">
                      <% @user.projects.each do |p| %>
                        <ul class="list-group no-radius m-b-none m-t-n-xxs list-group-lg no-border">
                          <li class="list-group-item">
                            <span class="clear">
                              <% if current_user == @user %>
                                <small class="pull-right">
                                  <%= link_to (t "application.edit"), edit_project_path(p) %> |
                                  <%= link_to (t "application.delete"), p, method: :delete, data: { confirm: (t "application.confirm") } %>
                                </small>
                              <% end %>
                              <strong class="block">
                                <%= link_to p.title, project_path(p) %>
                              </strong>
                            </span>
                          </li>
                        </ul>
                      <% end %>
                      <div style="padding:10px 20px;">
                        <% if current_user == @user %>
                        <%= link_to "Add New", new_project_path, id: "new_link" %>
                        <% end %>
                      </div>
                    </div>
                    <div class="tab-pane" id="myvideos">
                      <div class="wrapper">
                        <div style="padding-bottom:20px;">
                          <%= link_to "View All", videos_path, class: "btn" %>
                          <% if current_user == @user %>
                            | <%= link_to "Add New", new_video_path, id: "new_video", class: "btn" %>
                          <% end %>
                        </div>
                        <div id="video_url">
                          <% @user.videos.take(4).each do |video| %>
                          <div class="col-md-8">
                            <h4><%= link_to video.title, video %></h4>
                            <p><%= video.description %></p>
                            </br><a href="<%= video.video_link %>"></a>
                          </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </section>
            </aside>
          </section>
        </section>
      </section>
      <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen" data-target="body"></a>
    </section>
    <!-- /.vbox -->
  </section>
</body>