config/routes.rb
Alumni::Application.routes.draw do
scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root :to => 'main#index'
  resources :users do
    resources :links
  end
  resources :users do
    collection { post :search, to: 'users#index' }
  end
  resources :users do
    resources :videos
  end
  resources :projects do
    resources :links
  end
  resources :videos
  resources :links
  resources :addresses
  get 'remote%2FgetStates%2F:country', to:'addresses#getStates'
  resources :users do
    resources :inquiries, :only => [:new, :create] do
      get 'thank_you', :on => :collection
    end
  end
end
match '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
match '', to: redirect("/#{I18n.locale}")

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :description, :title, :video_link
  belongs_to :user
  validates_presence_of :title, :video_link
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
    if current_user.nil?
      redirect_to :root
    else
      @videos = current_user.videos
    end
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(params[:video])
    @video.user = current_user
    if @video.save
      flash[:notice] = "Video has been saved."
      redirect_to videos_path
    else
      flash[:alert] = "Video has not been saved."
      render :action => "new"
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update_attributes(params[:video])
      flash[:notice] = "Video has been updated."
      redirect_to @video
    else
      flash[:alert] = "Video has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:notice] = "Video has been deleted"
    redirect_to current_user
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video, id: "new_video_form", :html => {:class => 'form-inline'}) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.input :description, id: "project_description", class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.input :video_link, class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.submit "Save Video", class: "btn btn-twitter" %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">Edit Video</span>
    <div class="row m-n">
      <div class="col-md-4 col-md-offset-4 m-t-lg">
        <section class="panel">
          <header class="panel-heading text-center">
            Hilarious.
          </header>
          <div class="panel-body">
            <%= render "form" %>
          </div>
        </section>
      </div>
    </div>
  </section>
</body>

app/views/videos/index.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>

  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">My Videos</span>
    <div id="video_url">
      <% @videos.each do |video| %>
      <div class="col-lg-4">
        <section class="panel">
          <div class="panel-body">
            <h4><%= link_to video.title, video %></h4>
            <p><%= video.description %></p>
            </br><a href="<%= video.video_link %>"></a>
          </div>
        </section>
      </div>
      <% end %>
    </div>
  </section>
</body>

app/views/videos/new.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">New Video</span>
    <div class="row m-n">
      <div class="col-md-4 col-md-offset-4 m-t-lg">
        <section class="panel">
          <header class="panel-heading text-center">
            This better be a good one.
          </header>
          <div class="panel-body">
            <%= render "form" %>
          </div>
        </section>
      </div>
    </div>
  </section>
</body>

app/views/videos/new.js.erb
$('#new_video').hide().after('<%= j render("form") %>')

app/views/videos/show.html.erb
<div class="container_inner">
  <% if user_signed_in? %>
    <div class="signed_in">
      <p style="color:#555; line-height:16px; margin:0px;"><%= t "application.signed_in_as" %> <%= current_user.email %></p>
    </div>
  <% end %>

  <%= link_to (t "application.back"), :back %>
  <% if current_user == @video.user %>
    | <%= link_to 'Edit', edit_video_path %>
    | <%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %>
    | <%= link_to "Add New", new_video_path, id: "new_video" %>
  <% end %>
  <div id="video_url">
    <h2><%= @video.title %></h2>
    <p><%= @video.description %></p>
    <p><a href="<%= @video.video_link %>"></a></p>
    <p><%= link_to "View All", videos_path %></p>
  </div>
</div>