config/routes.rb
Alumni::Application.routes.draw do
scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root :to => 'main#index'
  resources :users do
    resources :links
  end
  resources :users do
    collection { post :search, to: 'users#index' }
  end
  resources :users do
    resources :videos
  end
  resources :projects do
    resources :links
  end
  resources :videos
  resources :links
  resources :addresses
  get 'remote%2FgetStates%2F:country', to:'addresses#getStates'
  resources :users do
    resources :inquiries, :only => [:new, :create] do
      get 'thank_you', :on => :collection
    end
  end
end
match '*path', to: redirect("/#{I18n.locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.locale}/" }
match '', to: redirect("/#{I18n.locale}")

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :image, :date_deployed

  belongs_to :user
  has_many :links, :as => :owner

  validates_presence_of :title

  mount_uploader :image, ProjectImageUploader

  def ordered_links
    return self.links.sort_by { |link| link.url_type}
  end

  def associated_user
    return self.user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    if current_user.nil?
      redirect_to :root
    else
      @projects = current_user.projects
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    @project.user = current_user
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to projects_path
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def show
    @project = Project.find(params[:id])
    @object = @project
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been deleted"
    redirect_to current_user
  end

end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, :html => {:class => 'form-inline'}) do |f| %>
  <%= f.error_notification %>
  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.input :description, id: "project_description", class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.input :date_deployed, :include_blank => true, class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.input :image, class: "form-control" %>
  </div></br></br>
  <div class="form-group">
    <%= f.submit "Save Project", class: "btn btn-twitter" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">Edit Project</span>
    <div class="row m-n">
      <div class="col-md-4 col-md-offset-4 m-t-lg">
        <section class="panel">
          <header class="panel-heading text-center">
            Sweet project you got going on!
          </header>
          <div class="panel-body">
            <%= render "form" %>
          </div>
        </section>
      </div>
    </div>
  </section>
</body>

app/views/projects/index.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html"><%= t " .my_projects" %></span>
    <section class="scrollable wrapper">
      <div class="tab-content">
        <div class="tab-pane active" id="static">
          <div class="row">
            <div class="col-md-8 col-md-offset-2 m-t-lg">
              <section class="panel">
                <header class="panel-heading">
                  Check out all these cool projects!
                </header>
                <div class="table-responsive">
                  <table class="table table-striped b-t text-sm">
                    <thead>
                      <tr>
                        <th><%= t "application.image" %></th>
                        <th><%= t "application.title" %></th>
                        <th><%= t "application.description" %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @projects.each do |p| %>
                        <tr>
                          <td><%= link_to (image_tag p.image_url(:thumb).to_s), p %></td>
                          <td><%= link_to p.title, project_path(p) %></td>
                          <td><%= link_to p.description, project_path(p) %></td>
                          <% if current_user == @user %>
                            <td><%= link_to (t "application.edit"), edit_project_path(p) %></td>
                            <td><%= link_to (t "application.delete"), p, method: :delete, data: { confirm: (t "application.confirm") } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <footer class="panel-footer">
                  <%= link_to (t " application.add_project"), new_project_path, id: "new_link", remote: true %>
                </footer>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

app/views/projects/new.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html">New Project</span>
    <div class="row m-n">
      <div class="col-md-4 col-md-offset-4 m-t-lg">
        <section class="panel">
          <header class="panel-heading text-center">
            Let's see your latest project.
          </header>
          <div class="panel-body">
            <%= render "form" %>
          </div>
        </section>
      </div>
    </div>
  </section>
</body>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/projects/show.html.erb
<body data-spy="scroll" data-target="#header" class="landing">
  <header id="header" class="navbar navbar-fixed-top bg-primary dk" style="background:#b43d3d;"  data-spy="affix" data-offset-top="1">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">Code Fellows</a>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><em>Alumni Portal</em></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "English", locale: "en" %></small></p>
      <p class="navbar-text pull-left text-muted hidden-xs hidden-sm"><small class="text-muted"><%= link_to_unless_current "中文", locale: "ch" %></small></p>
      <ul class="nav navbar-nav pull-right">
        <li class="hide">
          <a href="#header">Home</a>
        </li>
        <li class="hidden-xs"><%= link_to (t "application.home"), root_path %></li>
        <li class="hidden-xs"><%= link_to (t "application.alumni"), users_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs"><%= link_to (t "application.my_profile"), current_user %></li>
          <li class="hidden-xs"><%= link_to (t "application.my_projects"), projects_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_out"), destroy_user_session_path, :method => :delete %></li>
          <% else %>
          <li class="hidden-xs"><%= link_to (t "application.sign_up"), new_user_registration_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in"), new_user_session_path %></li>
          <li class="hidden-xs"><%= link_to (t "application.sign_in_with_twitter"), user_omniauth_authorize_path(:twitter) %></li>
        <% end %>
      </ul>
    </div>
  </header>
  <section id="content" class="m-t-lg wrapper-md animated fadeInUp" style="padding-top:80px;">
    <span class="nav-brand" href="index.html"><%= @project.title %></span>
    <div class="row m-n">
      <div class="col-md-8 col-md-offset-2 m-t-lg">
        <section class="panel">
          <header class="panel-heading text-center">
            This looks like a promising project. Eh?
            <div style="float:right;">
              <% if current_user == @project.user %>
                <%= link_to (t " application.add_project"), new_project_path, id: "new_link" %> |
                <%= link_to (t "application.edit"), edit_project_path %> |
                <%= link_to (t "application.delete"), p, method: :delete, data: { confirm: (t "application.confirm") } %>
              <% end %>
            </div>
          </header>
          <div class="panel-body">
            <b><%= t " application.description" %>:</b>
            <%= @project.description %>
            </br></br>
            <b><%= t " .date_deployed" %>:</b>
            <% if !@project.date_deployed.nil? %>
              <%= @project.date_deployed.to_s(:date_deployed) %>
            <% end %>
            </br></br>
            <b><%= t ".project_links" %>:</b>
            </br></br>
            <%= render "links/links_form" %>
            <% if current_user == @project.user %>
              <%= link_to (t " application.add_link"), new_project_link_path(@object) %>
            <% end %>
            </br></br>
            <% if @project.image_url.present? then %>
              <b><%= t "application.screenshot" %>:</b></br>
              <div class="col-md-9 col-md-offset-1"><%= image_tag @project.image_url.to_s %></div>
            <% end %>
          </div>
        </section>
      </div>
    </div>
  </section>
</body>